# Generated by Django 4.2 on 2024-02-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company')),
                ('call_us', models.CharField(max_length=30)),
                ('email_us', models.EmailField(max_length=254)),
                ('subtitle', models.TextField(max_length=200)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('emails', models.TextField(max_length=100)),
                ('phones', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('mobile_app', models.TextField(max_length=300)),
                ('android_url', models.URLField(blank=True, null=True)),
                ('iphone_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
